server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "luan123"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
    youtube:
      playlistLoadLimit: 6
      searchEnabled: true

logging:
  level:
    root: INFO