server:
  port: 2333
  address: 0.0.0.0      # aceita conexões de qualquer IP
  password: "luan123"
  bufferDurationMs: 4000
  frameBufferDurationMs: 1000
  outputDelay: 0

lavalink:
  server:
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
    youtube:
      playlistLoadLimit: 6
      searchEnabled: true
    playerUpdateInterval: 5
    gc-warnings: false

logging:
  level:
    root: INFO
  showIP: true       # ✅ esta linha adiciona instrução para imprimir o IP no log